### ISSUE TITLE
Failed to execute command 'xcrun simctl openurl' when URL with two or more ampersand (&)

### ISSUE THREAD

**Issue by EgorovDmitry** [Subito-it/SBTUITestTunnelHost#10]
Hi, I faced with an issue with open urls when this URL contains two or more ampersands (&), for example _https://appenvironment.app.io/openspace.htm?acc=1005&path=inbox&ei=9130&et=task_

The whole command looks like:
`XCTestCase().host.executeCommand(xcrun simctl openurl 7A54E60C-296A-4238-A2A1-611D1B28A972 https://appenvironment.app.io/openspace.htm?acc=1005&path=inbox&ei=9130&et=task)`

Open URL command works when I use a link with one ampersand, for example:
`XCTestCase().host.executeCommand(xcrun simctl openurl 7A54E60C-296A-4238-A2A1-611D1B28A972 https://appenvironment.app.io/openspace.htm?acc=1005&path=inbox` 
but when I add the rest two parameters with ampersands my command hanging and failed with cause "The request timed out."

I tried to escape the sequence for these symbols but it still doesn’t work, could you help to figure out how can I pass these types of links

**Comment by EgorovDmitry** [comment]
Thank you for this amazing tool!
I have a question - will you update the binary for the new version? I downloaded version 2.0.0 and as I understand it has the old version of the binary file(1.2.0)

**Comment by tcamin** [comment]
Instead of updating the binary, I've added a build script.
