### ISSUE TITLE
Build_server.sh not generating server app

### ISSUE THREAD

**Issue by mgrene** [Subito-it/SBTUITestTunnelHost#13]
When I run the build_server.ph, I get the message, “Server app SBTUITestTunnerlServer.app successfully built!” However I cannot find such file anywhere. Before I had the file in the Binary and just ran it, but now after running the build_server, I still don’t see it. 
I may just be missing a step as I’m unfamiliar with the process.

**Comment by tcamin** [comment]
The SBTUITestTunnelServer.app app should be copied to the same folder of the script. I also improved the output log by including the resulting app path.
