### ISSUE TITLE
Include prebuilt server in the CocoaPod

### ISSUE THREAD

**Issue by ileitch** [Subito-it/SBTUITestTunnelHost#4]
It'd be great if the cocoapod included a prebuilt binary of the server. Currently we have to check in the server to source control, whereas we do not for our pods.

**Comment by tcamin** [comment]
Might [this](https://github.com/Subito-it/SBTUITestTunnelHost#executable-under-pods-folder) be a viable workaround?

**Comment by ileitch** [comment]
Ah yes, sorry I missed that part of the README. Looks like a viable workaround 👍

**Comment by tcamin** [comment]
I just added that 😄
