### ISSUE TITLE
'NSInternalInconsistencyException, reason: '[SBTUITestTunnelHost] Failed to get http response for action exec'

### ISSUE THREAD

**Issue by stelpk** [Subito-it/SBTUITestTunnelHost#5]
So we are trying to integrate your library into our project (in order to test if some push notifications are being successfully fired) but when we are running our project UI tests and we're executing the line below:

 **_host.executeCommand("xcrun simctl push ...")_** applying our project's bundle identifier and specific payload,

 the execution is being terminated and a "NSInternalInconsistencyException" is occurring with the message/reason: '[SBTUITestTunnelHost] Failed to get http response for action exec'.

I've tried to run your sample project (PushNotificationDemo) and the same problem was occurring again.

Could you please tell me If we're doing anything wrong? Is any extra configuration required? I've ran both projects (ours and your demo) using the latest versions of Xcode (11.4.1. && 11.5) and lots of different simulators (X - 13.1 , 11 Promo - 13.5 etc)

Thank you in advance.

![Screenshot 2020-07-03 at 9 56 00 AM](https://user-images.githubusercontent.com/20596682/86440654-86b10d80-bd13-11ea-9fc0-6fa2cabb6799.png)

**Comment by tcamin** [comment]
You will need to launch the mac host app companion ad described https://github.com/Subito-it/SBTUITestTunnelHost#mac-server-app
