### ISSUE TITLE
Assertion in launchCommand

### ISSUE THREAD

**Issue by BorisLys** [Subito-it/SBTUITestTunnelHost#8]
I have problem when use launchCommand.

```
import SBTUITestTunnelHost
import XCTest

class InstantReplay_iOSUITests: XCTestCase {
    
    var commandID: UUID!
    
    override func setUp() {
        // Put setup code here. This method is called before the invocation of each test method in the class.

        // In UI tests it is usually best to stop immediately when a failure occurs.
        continueAfterFailure = false
        
        // UI tests must launch the application that they test.
        let app = XCUIApplication()
        app.launch()

        commandID = host.launchCommand(
            "xcrun simctl io booted recordVideo --codec=h264 --mask=black --force /Users/Jeff/Desktop/test.mov"
        )
        
        _ = app.wait(for: .runningForeground, timeout: 5)
        
        _ = app.textFields.firstMatch.waitForExistence(timeout: 0.5)

        if let commandID = commandID {
            addTeardownBlock { [unowned self] in
                self.host.interruptCommand(with: commandID)
            }
        }
        else {
            print("No status!")
        }
    }

    func testExample() {
        let app = XCUIApplication()
            
        app.textFields.firstMatch.tap()
        
        let keyDelay = { return TimeInterval.random(in: 0...0.15) }

        "UITestExample@example.com".map(String.init).forEach {
            if ["@", "."].contains($0) {
                app.keys["more"].tap()
                XCTAssertTrue(app.keys[$0].waitForExistence(timeout: keyDelay()))
                app.keys[$0].tap()
                app.keys["more"].tap()
            }
            else if $0 == $0.uppercased(), !app.keys[$0].exists {
                app.buttons["shift"].tap()
                XCTAssertTrue(app.keys[$0].waitForExistence(timeout: keyDelay()))
                app.keys[$0].tap()
            }
            else {
                XCTAssertTrue(app.keys[$0].waitForExistence(timeout: keyDelay()))
                app.keys[$0].tap()
            }
        }
        
        app.buttons["Return"].tap()
        
        XCTAssertTrue(app.textFields.firstMatch.waitForExistence(timeout: 0.5))
    }
}
```

**Error:**
`** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '[SBTUITestTunnelHost] Message sending failed for action launch'
terminating with uncaught exception of type NSException`
<img width="1792" alt="Screenshot 2021-08-03 at 11 07 36" src="https://user-images.githubusercontent.com/38007083/127980924-0585292c-6e23-4f69-8506-6da225bed2eb.png">

**Comment by tcamin** [comment]
You should be using `executeCommand` instead of `launchCommand` as per [documentation](https://github.com/Subito-it/SBTUITestTunnelHost#launching-shell-commands)

**Comment by BorisLys** [comment]
I rewrite the method and still get an assert
`host.executeCommand("xcrun simctl io booted recordVideo --codec=h264 --mask=black --force /Users/user/Desktop/test.mov")`
<img width="1286" alt="Screenshot 2021-08-04 at 07 38 16" src="https://user-images.githubusercontent.com/38007083/128123103-f858fbeb-895b-4d5f-b75b-4a2df719547e.png">

**Comment by tcamin** [comment]
Is the Mac host app running?

**Comment by BorisLys** [comment]
yes. If i code:
`host.executeCommand("pwd")` - it's work
But when i try use:
`host.executeCommand("xcrun simctl io booted recordVideo --codec=h264 --mask=black --force /Users/user/Desktop/test.mov")`
I get assert

**Comment by tcamin** [comment]
Did you try 

`host.executeCommand("/usr/bin/xcrun simctl io booted recordVideo --codec=h264 --mask=black --force /Users/user/Desktop/test.mov")`

**Comment by BorisLys** [comment]
Yes and i have the same assert

**Comment by tcamin** [comment]
You might need to debug this on both sides, run your tests and the server app in Xcode and try to understand what is going wrong.
